### ISSUE TITLE
Settings - create component for settings view

### ISSUE THREAD

**Issue by SmilingKat** [codeforireland2/transparentwater_mobileapp#43]
1. Create an empty component and add to the tab view in the main.
2. add an image for the settings tab display
3. create layout for the component in two sections 

This will display the settings data:
- Access to location (On /Off)
- Notifications (On /Off)
-display of favourite regions this can be a scrollable listview (for now just add the following items: Region 1, Region 2, Region 3)

**Comment by gkemp94** [comment]
So for this, the notifications & location access is all controlled on the system level. (i.e. we can prompt the user for access to their location & ability to send them notifications, but once they've answered there is no changing it on the app level), so I believe that these are things we should leave to the system. I proposed the following items:

- Notification cities (Basically a multiple checkbox that will allow the user to select which counties they want to be notified about & which they see on their list view)
- About the App (basically a quick blurb about the contributors and code for Ireland and a disclaimer stating that our information is only as good as the information we get from Irish water and that we claim no responsibility for issues relating to the accuracy of the information displayed etc etc. )
